### ISSUE TITLE
Permissions Problem

### ISSUE THREAD

**Issue by yasons-zz** [Bleuzen/RPGHealthPlus#1]
Well, I'm really a newbie in plugin or etc.
I don't know how to add permission, should I make file permissions.yml then paste command & permission?
Because I've set the start HP, but the health still normal and I'm still wondering why only 1 user and it is the OP only able to get health plus. The other regular players didn't appear in player.yml (did they need to up their level first, then will appear?)

Thank you.

**Comment by Bleuzen** [comment]
By default, OP users have all permissions and not OP have no permissions.
RPGHealth creates players in players.yml only if they have the permission "rpghealth.hp", so you have to add it to all of your users.
The easiest way to do this is to use a permissions plugin. I recommend PermissionsEx.

Setup:
1. Download and install PEx from: https://dev.bukkit.org/projects/permissionsex
2. Restart your server

 -- In PEx you can create different groups and add players to groups --
 -- I will skip group setup for now, because you only need one group for this to work, which already exists. --

The default group, which contains all players (thats what we want) is called "default".
So the only thing we need to do is to add the permission "rpghealth.hp" to the PEx group "default".

3. Type this into your console:

pex group default add rpghealth.hp

4. (optional, but I recommend it) Restart the server again

 -- Now test it with a player, who is not OP and he / she should appear in player.yml --
 -- That's it ;) --
