### ISSUE TITLE
Player's can't level up their hearts even with rpghealth.hp permission. 

### ISSUE THREAD

**Issue by Ellie124** [Bleuzen/RPGHealthPlus#3]
Hey, I'm not sure if this is an error from the plugin or something I'm doing wrong but I'm using the (1.9) 1.2.4 or 5? version (because the other 1.9 versions don't work for some reason) and my players can't seem to obtain xp and level up their hearts. I use group manager and added the rpghealth.hp permission to my groups (I even tested permissionsEX) but it doesn't seem to do anything. The only way for a player to get hearts is if they are op so I can't tell whether it's a permission problem or something else?

**Comment by Bleuzen** [comment]
You must use this old version because 1.2.4 is the latest version which supports MC 1.9 (v1_9_R1).
You should update your server ;)

Nevermind ... if you want to stay with 1.9:
In this old version you are using, you also have to add your players the permission "rpghealth.earnxp". This got merged with a newer version into "rpghealth.hp", but not in 1.2.4 already.

**Comment by Ellie124** [comment]
Ah legend! Thank You.  It works now (:
