### ISSUE TITLE
1.13?

### ISSUE THREAD

**Issue by Midnight9746** [Bleuzen/RPGHealthPlus#5]
Will the plugin ever support 1.13?

I use the plugin a lot and was sad when it died on 1.13. Other players on the server were sad as well.

**Comment by Nathan77540** [comment]
You can still take the source, and then re-compile it with spigot 1.13 ^^

**Comment by Midnight9746** [comment]
Oh nice, complete noob question: how do I do that? XD

**Comment by Bleuzen** [comment]
Will see what I can do. Well, the reason behind my projects is: I do them because I need / use them.
I only develop what I need and use. I wouldn't have the time to maintain other projects without an use for me.

Now I have other time consuming projects and a lot going on in real life. Also I haven't played Minecraft for about a year, so I don't use this plugin anymore. So there is no big reason for me to continue developing it.

But this doesn't mean the project is dead.
Since I see there is still interest, I may update it.
But please understand that other projects and real life things are currently more important to me, so this project has pretty low priority.
I will update it when I have some time. But I will not add new features. Don't know when this will happen and how fast.
Until then, if someone wants to help: This is open source! ;)

Thanks for understanding and sorry that you have to wait.

**Comment by Bleuzen** [comment]
@Midnight9746 Ok new beta up for testing:
https://www.spigotmc.org/resources/rpghealthplus.6176/download?version=236687

I hope it works on 1.13.
But new mobs (if there are some in 1.13) are not added yet (I don't know what's new in 1.13 since I never played it).

Please test / report
- if it works at all on your 1.13 server
- if you found missing mobs (maybe I will add them when I have time to make a 'full' 1.13 version)

**Comment by Midnight9746** [comment]
I will go test it, but there is new mobs.

- Dolphin
- Turtle
- Phantom
- Drowned
- Fish
  - Cod 
  - Salmon 
  - Pufferfish 
  - Tropical Fish

**Comment by Bleuzen** [comment]
Btw. the current version can already handle the new mobs, I just haven't found time to add them to the config file.

You can try to add them yourself to your existing config file, for example just under last mob, add:
`DOLPHIN: 4`
`TURTLE: 3`
...
If the names are correct it should work.
