### ISSUE TITLE
1.14.3 Update

### ISSUE THREAD

**Issue by pkhodadi** [Bleuzen/RPGHealthPlus#6]
I would like to know when the 1.14.3 supported version of this plugin will be released.

**Comment by Bleuzen** [comment]
I'm sorry, but I'm not really active at this plugin anymore. My life changed, I don't play Minecraft anymore and have other projects to work on.

In the latest version I removed all MC version specific code, so that it should at least start on newer server versions. Does it still work on 1.14.3? (should, but I have no time to test it rn)

If it starts, only things missing are the new mobs in the config file. But you can add the new mobs yourself. Just put their name in UPPERCASE in the config file in a new line as for the other mobs and it should work.

**Comment by Bleuzen** [comment]
Hi!
Good news. I just released a new version today with some code updates and all the new mobs for Minecraft 1.16 :)

That said, since I haven't played Minecraft for a longer time now and I don't know the new mobs in game, I'm not sure if the default XP values in the config are good for them.
If you suggestions for better defaults, give me a hint.

Also, this version is not well tested yet. I will leave this to you for now. If you give it a try, some feedback if it still works would be nice.
